"""Solution response data — Supply Chain & Logistics (SCM-001 → SCM-052)"""

SOLUTIONS_SCM = {
# ═══════════════════════════════════════════════════════════════
#  8.1  SALES & ORDER MANAGEMENT  (SCM-001 → SCM-012)
# ═══════════════════════════════════════════════════════════════
"SCM-001": {"code": "S", "summary": "Standard D365 Sales — sales order entry with customer, product, quantity, price, currency, delivery, Incoterms, and instructions.",
    "detail": "<p>D365 <strong>Sales Order Processing</strong>: orders with customer, product variant (species/presentation/quality/weight class/packaging), quantity (kg or units), price, currency, delivery date/address, Incoterms, transport mode, and special instructions. Multiple channels: direct entry, EDI, customer portal, API integration — all result in standard D365 sales orders.</p>"},
"SCM-002": {"code": "C", "summary": "D365 Electronic Messaging — automated EDI order intake (EDIFACT ORDERS / PEPPOL) mapped to D365 sales orders.",
    "detail": "<p>EDI order processing: large retail/foodservice customers send purchase orders via EDI (EDIFACT ORDERS or PEPPOL). D365 Electronic Messaging parses incoming EDI → auto-creates sales orders with all order details. Acknowledgment (ORDRSP) sent back to customer. Exception handling for: unknown products, unavailable quantities, or price mismatches.</p>"},
"SCM-003": {"code": "S", "summary": "Standard D365 catch-weight — variable-weight order handling where exact quantity confirmed at dispatch based on actual weights.",
    "detail": "<p>Variable-weight orders: customer orders nominal quantity (e.g., 500 kg of 3-4 kg HOG salmon). D365 catch-weight manages: order in nominal kg, actual fulfilment based on available batch weights at dispatch. Invoice adjusted to actual delivered catch-weight. Weight tolerances configurable per customer/product.</p>"},
"SCM-004": {"code": "S", "summary": "Standard D365 Sales Agreements — contract management with volumes, pricing, delivery schedules, and auto-renewal tracking.",
    "detail": "<p>D365 <strong>Sales Agreements</strong>: framework contracts with committed volume, pricing (fixed or index-linked formula), delivery schedule, contract period, and auto-renewal terms. Sales orders created against agreements drawing down committed volumes. Commitment tracking: committed vs. delivered, remaining, compliance %.</p>"},
"SCM-005": {"code": "C", "summary": "D365 allocation rules — spot vs. contract differentiation with contract-first allocation of available production.",
    "detail": "<p>Spot vs. contract allocation: D365 sales order types differentiate contract and spot sales. Allocation rules: contract orders allocated first from available/planned production, remaining capacity available for spot. Spot sales tracked separately for price analytics and market intelligence. Allocation dashboard shows: committed vs. available by product/week.</p>"},
"SCM-006": {"code": "S", "summary": "Standard D365 Trade Agreements — price lists by customer/group with fixed, formula-based, volume-tiered, and promotional pricing.",
    "detail": "<p>D365 <strong>Trade Agreements &amp; Pricing</strong>: base price per product variant, customer-specific discounts/premiums, volume-tier pricing, index-linked formulas (Fish Pool ± spread), seasonal price versioning, promotional pricing with date validity, and multi-currency (NOK, EUR, USD, GBP). Price determination hierarchy: customer-specific → customer group → base price list.</p>"},
"SCM-007": {"code": "C", "summary": "D365 + Azure integration — salmon price index feed (Fish Pool, Nasdaq) for automated spot price reference and contract calculations.",
    "detail": "<p>Salmon index integration: market price indices (Fish Pool, Nasdaq Salmon Index) imported via Azure Logic Apps → D365 as reference prices. Used for: index-linked contract price calculation (index ± premium/discount), spot sale pricing decisions, and market position analysis. Price feed updated daily/weekly per index publication schedule.</p>"},
"SCM-008": {"code": "S", "summary": "Standard D365 ATP — available-to-promise based on inventory + planned production (harvest plan) – committed orders.",
    "detail": "<p>D365 <strong>Available-to-Promise (ATP)</strong>: on-hand + planned production (harvest schedule from AquaMonitor + processing schedule) − committed orders = available per product per date. Order promising suggests earliest date if requested not feasible. Allocation priority rules for supply-constrained periods.</p>"},
"SCM-009": {"code": "C", "summary": "D365 allocation rules — order prioritization when supply constrained based on contract, customer tier, margin, and strategy.",
    "detail": "<p>Order allocation: when available product &lt; total demand, allocation rules prioritise: 1) contract obligations, 2) premium customer tier, 3) margin contribution, 4) strategic market requirements. Allocation workspace shows available supply vs. demand with manual override capability. Allocation decisions documented for sales team visibility.</p>"},
"SCM-010": {"code": "S", "summary": "Standard D365 Sales — order amendments and cancellation with audit trail and downstream plan adjustment.",
    "detail": "<p>Order amendments: quantity, date, and product changes processed in D365 with full audit trail. Cancellation with reason code. Amendments auto-adjust: dispatch plan, production allocation, and invoicing. Version history shows original order vs. all amendments. Approval workflow for significant changes.</p>"},
"SCM-011": {"code": "S", "summary": "Standard D365 order tracking — real-time status visibility: confirmed → in production → packed → dispatched → delivered.",
    "detail": "<p>Order status tracking: D365 order lifecycle status visible in real-time: Open → Confirmed → In Production → Packed → Dispatched → Delivered → Invoiced. Sales team views via D365 sales workspace. Customer visibility via optional Power Pages portal (SCM-012). Automated notifications at key status changes.</p>"},
"SCM-012": {"code": "D", "summary": "Desirable — Power Pages customer portal for order placement, tracking, invoice viewing, certificates, and claims.",
    "detail": "<p>Customer self-service portal (Power Pages — desirable): order placement from product catalogue, real-time order status tracking, invoice/credit note viewing, certificate downloads (health certificates, CoA), and quality claims submission. May be deferred to post-go-live enhancement.</p>"},

# ═══════════════════════════════════════════════════════════════
#  8.2  PROCUREMENT & VENDOR MANAGEMENT  (SCM-013 → SCM-023)
# ═══════════════════════════════════════════════════════════════
"SCM-013": {"code": "S", "summary": "Standard D365 Procurement — full workflow: requisition → approval → PO → goods receipt → invoice matching → payment.",
    "detail": "<p>D365 <strong>Procurement &amp; Sourcing</strong>: purchase requisition (self-service) → approval workflow → purchase order → vendor confirmation → goods receipt → three-way invoice matching → payment. Full lifecycle tracking per PO.</p>"},
"SCM-014": {"code": "S", "summary": "Standard D365 workflow — configurable purchase approval matrix by value, category, cost centre, and requestor role.",
    "detail": "<p>Approval matrix: D365 workflow routes approvals by: amount thresholds (e.g., &lt;10k auto, 10-50k dept manager, 50k+ director), procurement category, cost centre, and requestor role. Multi-level sequential or parallel approvals. Mobile approval via D365 mobile app. Delegation for absent approvers.</p>"},
"SCM-015": {"code": "S", "summary": "Standard D365 Purchase Agreements — blanket/framework agreements with agreed terms, call-off orders, and utilisation tracking.",
    "detail": "<p>D365 <strong>Purchase Agreements</strong>: long-term framework agreements with: agreed prices, quantity commitments, delivery terms, and validity period. Call-off purchase orders drawn against the agreement. Utilisation tracking: committed vs. consumed volume/value, remaining balance, and agreement compliance.</p>"},
"SCM-016": {"code": "C", "summary": "D365 vendor evaluation + Power BI — systematic vendor scoring on delivery, quality, price, sustainability, and financial stability.",
    "detail": "<p>Vendor evaluation: D365 vendor performance data combined in Power BI scorecards: delivery performance (OTIF%), quality (NCR count, rejection rate), price competitiveness (vs. market), sustainability criteria (certifications, ESG scores), and financial indicators. Composite weighted score per vendor group. Quarterly review cycle.</p>"},
"SCM-017": {"code": "C", "summary": "D365 vendor master + Quality — vendor qualification with approved list, certifications, audit results, and requalification schedule.",
    "detail": "<p>Vendor qualification: approved vendor list maintained in D365 vendor master. Certification tracking (food safety, environmental, ASC/MSC) with expiry dates and renewal alerts. Audit results recorded. Requalification schedule with Power Automate reminders. Non-approved vendors blocked from PO creation.</p>"},
"SCM-018": {"code": "S", "summary": "Standard D365 Procurement — PO status tracking throughout lifecycle: created → sent → acknowledged → received → invoiced → closed.",
    "detail": "<p>PO lifecycle tracking: status visible at each stage. Vendor acknowledgment (confirmation) tracked. Partial receipt handling for split deliveries. Over/under-delivery tolerance. Back-order management for undelivered balances. PO status dashboard for procurement team.</p>"},
"SCM-019": {"code": "S", "summary": "Standard D365 receiving — goods receipt against PO with actual quantity, quality inspection, batch assignment, and location.",
    "detail": "<p>Goods receipt: receipt against PO with actual quantity/catch-weight, quality inspection trigger (via quality associations), batch/lot assignment, warehouse location confirmation, and date recording. Product receipt posting updates inventory on-hand and creates AP accrual.</p>"},
"SCM-020": {"code": "S", "summary": "Standard D365 returns — return-to-vendor process with return order, debit note, goods shipment, and AP adjustment.",
    "detail": "<p>Vendor returns: return order created with reason code and linked to original PO. Debit note generated. Goods shipped back or disposed (with vendor agreement). AP credit processed. Return reasons tracked feeding vendor evaluation scoring.</p>"},
"SCM-021": {"code": "S", "summary": "Standard D365 RFQ — request for quotation to multiple vendors with comparison, bid selection, and PO conversion.",
    "detail": "<p>D365 <strong>RFQ Process</strong>: send RFQ to multiple vendors specifying requirements. Receive and compare quotes in D365 (side-by-side comparison). Select winning bid with documented justification. Convert accepted quote to purchase order. RFQ history maintained for audit.</p>"},
"SCM-022": {"code": "C", "summary": "D365 + Power BI — spend analytics by category, vendor, location, and period with consolidation opportunities and price trends.",
    "detail": "<p>Procurement analytics: Power BI dashboards with spend analysis by: procurement category, vendor, cost centre, location, period. Trend analysis: price changes, volume patterns. Consolidation opportunities identified: multiple vendors for same category, maverick spending. Contract compliance: actual spend vs. agreement terms.</p>"},
"SCM-023": {"code": "C", "summary": "D365 vendor attributes + Microsoft Sustainability Manager + Power BI — procurement sustainability with ESG scoring, Scope 3 carbon tracking, and sourcing policy compliance.",
    "detail": "<p>Sustainable procurement: vendor ESG scores tracked as D365 vendor attributes. Environmental certifications (ISO 14001, ASC, MSC) with validity tracking. <strong>Microsoft Sustainability Manager</strong> calculates Scope 3 upstream emissions from procurement data — particularly feed (NordHav's largest carbon impact at ~145,000 tCO2e), transport, and packaging. Supplier carbon intensity benchmarking and sustainable sourcing policy compliance monitoring. Power BI procurement sustainability dashboard with Sustainability Manager connector.</p>"},

# ═══════════════════════════════════════════════════════════════
#  8.3  INVENTORY & WAREHOUSE  (SCM-024 → SCM-036)
# ═══════════════════════════════════════════════════════════════
"SCM-024": {"code": "S", "summary": "Standard D365 Inventory — multi-location tracking across processing plants, cold stores, smolt facilities, and feed barges.",
    "detail": "<p>D365 multi-location: inventory per site (Austevoll, processing plants, smolt facilities) and warehouse (raw material, cold store, frozen, consumables, feed barges). Real-time on-hand by site, warehouse, location, product, batch, status. Inventory dimensions: site, warehouse, location, batch, serial.</p>"},
"SCM-025": {"code": "S", "summary": "Standard D365 batch tracking — mandatory batch/lot management with traceability for receipt, transfer, production, and dispatch.",
    "detail": "<p>Batch tracking: mandatory batch assignment at purchase receipt, production output, and transfer receipt. Batch attributes: origin, quality, production date, best-before. Full forward/backward traceability via D365 batch trace.</p>"},
"SCM-026": {"code": "S", "summary": "Standard D365 catch-weight — dual-unit inventory (count + actual weight) for biological products with inherent weight variability.",
    "detail": "<p>Catch-weight inventory: tracked in both nominal unit (count/cases) and actual weight (kg). Weight captured at every transaction. Financial settlement uses actual weight. Supports the inherent variability of biological products where each piece differs.</p>"},
"SCM-027": {"code": "S", "summary": "Standard D365 batch attributes — shelf-life tracking with best-before dates and FEFO picking enforcement for finished goods.",
    "detail": "<p>Shelf-life &amp; FEFO: best-before dates per batch. FEFO picking enforced for perishable goods dispatch. Alerts on approaching expiry. Expired product blocked from sale. Shelf-life remaining visible in inventory queries.</p>"},
"SCM-028": {"code": "S", "summary": "Standard D365 WMS — location-based warehouse management with zones, aisles, racks, levels, and temperature classification.",
    "detail": "<p>D365 WMS location management: zone (receiving, staging, production, chilled, frozen, dispatch), aisle, rack, level. Temperature zone classification per location. Location capacity tracking. Directed putaway by temperature, product type, available space.</p>"},
"SCM-029": {"code": "S", "summary": "Standard D365 WMS mobile — barcode/scan operations for goods receipt, putaway, picking, counting, and dispatch verification.",
    "detail": "<p>D365 Warehouse mobile app: barcode scanning for all warehouse operations — goods receipt, putaway, movement, picking, packing, cycle counting, and dispatch. Works on Android/iOS. Ruggedised hardware options for cold environments.</p>"},
"SCM-030": {"code": "S", "summary": "Standard D365 WMS — cycle counting and full stocktake with variance investigation, approval, and adjustment posting.",
    "detail": "<p>Stock counting: configurable cycle counting plans by value class (ABC), product type, and zone. Full periodic stocktake support. Mobile counting workflow. Variance investigation with recount and supervisor approval. Adjustments posted with reason codes. Accuracy KPI tracking.</p>"},
"SCM-031": {"code": "S", "summary": "Standard D365 Inventory — packaging material tracking: EPS boxes, cartons, labels, film, bags, pallets with min stock alerts and reorder.",
    "detail": "<p>Packaging material inventory: item master for all packaging with reorder points, safety stock, lead times. MRP generates planned purchase orders. Consumption tracked via production BOM. Stock alerts for low inventory.</p>"},
"SCM-032": {"code": "S", "summary": "Standard D365 Inventory + Asset Management — spare parts inventory with min/max levels, reorder, and maintenance work order linking.",
    "detail": "<p>Spare parts: part master in D365 with location, min/max levels, reorder point. Usage tracked via Asset Management work orders. MRP triggers replenishment. Cost allocated to maintenance work orders.</p>"},
"SCM-033": {"code": "C", "summary": "D365 Inventory + AquaMonitor — feed barge inventory per sea site: feed type, quantity, silo allocation, deliveries, and consumption.",
    "detail": "<p>Feed barge inventory: feed tracked per barge/site with: feed type, quantity (tonnes), silo allocation, delivery history, consumption rate. AquaMonitor integration provides consumption data. Replenishment alerts. Delivery scheduling coordinated with feed supplier.</p>"},
"SCM-034": {"code": "S", "summary": "Standard D365 Inventory — consumables tracking at operational sites: chemicals, treatments, PPE, cleaning materials.",
    "detail": "<p>Consumables inventory: chemicals, treatment supplies, PPE, cleaning materials tracked per site. Min stock levels and reorder points. Purchase requisition generation on low stock. Usage recording per operational activity.</p>"},
"SCM-035": {"code": "S", "summary": "Standard D365 inventory valuation — FIFO or weighted average consistent with accounting policy for financial reporting.",
    "detail": "<p>Inventory valuation: FIFO (or weighted average) per accounting policy. Standard cost for manufactured items with variance analysis. Inventory value report by product, location, cost category. Period-end revaluation with variance posting.</p>"},
"SCM-036": {"code": "S", "summary": "Standard D365 Inventory — write-down and disposal recording for quality issues, expiry, or damage with financial postings.",
    "detail": "<p>Write-down &amp; disposal: inventory adjustment journals for: quality downgrade (revalue to lower price), expiry write-off, damage disposal. Each with reason code and approval workflow. Financial postings to appropriate GL accounts (loss/write-off). Audit trail on all adjustments.</p>"},

# ═══════════════════════════════════════════════════════════════
#  8.4  LOGISTICS & TRANSPORTATION  (SCM-037 → SCM-047)
# ═══════════════════════════════════════════════════════════════
"SCM-037": {"code": "S", "summary": "Standard D365 TMS — outbound transport planning based on orders, carrier schedules, routes, and delivery windows.",
    "detail": "<p>D365 <strong>Transportation Management</strong>: carrier selection, route planning, load building, and shipment scheduling. Considers: confirmed orders, carrier availability, route optimisation, delivery windows, and temperature requirements.</p>"},
"SCM-038": {"code": "S", "summary": "Standard D365 TMS — carrier management with contract terms, rate cards, performance tracking, and qualification.",
    "detail": "<p>Carrier management: contract terms, rate cards (per route/kg/pallet), performance tracking (OTIF%, damage rate), carrier qualification status. Rate comparison for carrier selection. Periodic carrier review.</p>"},
"SCM-039": {"code": "S", "summary": "Standard D365 TMS — multi-modal transport: truck, air, sea (container), and combined modes with shipment tracking across legs.",
    "detail": "<p>Multi-modal: D365 TMS supports truck, air freight, sea freight (container), and combined modes. Shipment tracked across transport legs. Mode selection based on: destination, urgency, cost, and product requirements.</p>"},
"SCM-040": {"code": "S", "summary": "Standard D365 TMS — freight cost calculation per shipment based on carrier rates with allocation to orders/invoices.",
    "detail": "<p>Freight cost: rates per carrier/route/mode (weight, pallet, truck load, container). Cost allocated to individual sales orders within shipment. Carrier invoice matched against calculated freight. Margin impact visible in customer profitability.</p>"},
"SCM-041": {"code": "S", "summary": "Standard D365 TMS — shipment consolidation of multiple orders into efficient loads to optimise transport costs.",
    "detail": "<p>Shipment consolidation: multiple customer orders grouped into efficient loads (truck, container, air pallet). Load building considers: weight, volume, temperature compatibility, delivery route, and delivery windows. Consolidation reduces per-unit freight cost.</p>"},
"SCM-042": {"code": "S", "summary": "Standard D365 TMS + document generation — CMR, Bill of Lading, packing lists, and customs/export declarations.",
    "detail": "<p>Transport documentation: CMR waybill (road), Bill of Lading (sea), airway bill data (air), packing lists, and customs export documentation generated from D365 shipment data. Health certificates linked. All documents stored against shipment record.</p>"},
"SCM-043": {"code": "C", "summary": "D365 + customs broker integration — TVINN/Toll.no export declaration filing or data provision for customs brokers.",
    "detail": "<p>Export customs: D365 provides customs declaration data: HS tariff codes per product, origin, quantities, values, export permits. Integration with TVINN/Toll.no directly or via approved customs broker. Data formatted per Norwegian customs requirements.</p>"},
"SCM-044": {"code": "C", "summary": "D365 document management — health certificate tracking: Mattilsynet application, certificate numbers, shipment linking, and archiving.",
    "detail": "<p>Health certificates: application tracking (to Mattilsynet), certificate number recording, linking to D365 shipment/sales order, and document archiving in SharePoint. Certificate data requirements sourced from production batch quality records.</p>"},
"SCM-045": {"code": "C", "summary": "D365 TMS + carrier integration — shipment tracking: dispatched → in transit → at customs → delivered with customer visibility.",
    "detail": "<p>Shipment tracking: carrier integration provides status updates (collected, in transit, at hub, out for delivery, delivered). Status visible in D365 and optionally via customer portal. Temperature monitoring data from loggers linked.</p>"},
"SCM-046": {"code": "S", "summary": "Standard D365 TMS — freight invoice verification against expected costs with discrepancy flagging.",
    "detail": "<p>Freight invoice verification: carrier invoices matched against D365-calculated freight charges per shipment. Variances flagged for investigation. Approved freight invoices posted to AP. Cost variance reporting in Power BI.</p>"},
"SCM-047": {"code": "S", "summary": "Standard D365 Trade — Incoterms management (EXW, FCA, CPT, CIF, DAP, DDP, FOB, CFR) with correct cost/risk allocation.",
    "detail": "<p>Incoterms: all major Incoterms supported. Default per customer in customer master. Overridable per order. Cost and risk transfer points correctly reflected in: freight cost allocation, insurance responsibility, customs documentation, and revenue recognition.</p>"},

# ═══════════════════════════════════════════════════════════════
#  8.5  DEMAND & SUPPLY PLANNING  (SCM-048 → SCM-052)
# ═══════════════════════════════════════════════════════════════
"SCM-048": {"code": "S", "summary": "Standard D365 Demand Forecasting — forecast based on historical sales, contracts, seasonal patterns, and sales team adjustments.",
    "detail": "<p>Demand forecasting: statistical baseline from historical sales by product/customer/season. Manual adjustment by sales team (market intelligence, new customers, contracted volumes). Monthly buckets (3-12 months) and weekly (1-12 weeks). Forecast accuracy tracking (MAPE).</p>"},
"SCM-049": {"code": "S", "summary": "Standard D365 Master Planning — supply-demand balancing view showing available supply vs. committed demand by product and week.",
    "detail": "<p>Supply-demand balance: harvest plan (AquaMonitor) + processing schedule = available supply. Sales orders + forecast = demand. Net position per product per week. Surplus/deficit identification. Planning workspace with visual supply-demand chart.</p>"},
"SCM-050": {"code": "S", "summary": "Standard D365 Master Planning — production scheduling integration linking orders and forecast to processing and harvest plans.",
    "detail": "<p>Production-sales integration: sales orders + forecast → processing production schedule → harvest requirement. MRP/MPS aligns all plans. Material requirements (packaging, feed, consumables) derived from production plan.</p>"},
"SCM-051": {"code": "C", "summary": "D365 + Power BI — S&OP process support with aggregate plans, scenario modelling, consensus views, and executive tracking.",
    "detail": "<p>S&amp;OP support: D365 Master Planning provides the data foundation. Power BI dashboards: aggregate demand/supply plan, scenario comparison (optimistic/pessimistic/base), consensus forecast, and executive decision tracking. Monthly S&amp;OP cycle supported.</p>"},
"SCM-052": {"code": "S", "summary": "Standard D365 MRP — packaging material requirements generated from production plan and product mix driving procurement with lead times.",
    "detail": "<p>Packaging material planning: production plan + BOM → packaging requirements per material per period. MRP generates planned purchase orders with lead times. Packaging procurement aligned to production schedule for JIT availability.</p>"},
}
