"""Solution response data — Quality & Compliance (QAC-001 → QAC-040)"""

SOLUTIONS_QAC = {
# ═══════════════════════════════════════════════════════════════
#  9.1  QUALITY MANAGEMENT SYSTEM (QMS)  (QAC-001 → QAC-010)
# ═══════════════════════════════════════════════════════════════
"QAC-001": {"code": "P", "summary": "SharePoint + Power Automate (Gap G-05) — QMS document control with version management, approval, and distribution.",
    "detail": "<p>QMS document management via <strong>SharePoint + Power Automate</strong> (Gap G-05):</p><ul><li><strong>Library</strong>: SharePoint doc libraries by type: SOPs, work instructions, policies, forms, external standards</li><li><strong>Version control</strong>: SharePoint versioning — all changes tracked with version number, date, modifier, description</li><li><strong>Approval</strong>: Power Automate workflow: Draft → Review → Approve → Published. Multi-level for critical SOPs</li><li><strong>Metadata</strong>: document type, department, process area, revision date, review due, owner, status</li></ul>"},
"QAC-002": {"code": "P", "summary": "SharePoint + Power Automate (Gap G-05) — document approval workflow with electronic signatures and current-version enforcement.",
    "detail": "<p>Document approval: Power Automate routes documents: author → reviewer(s) → approver. Electronic signature/approval recorded. Only the current approved version accessible to operational staff (previous versions archived). Approval status and history maintained per document.</p>"},
"QAC-003": {"code": "P", "summary": "SharePoint + Power Automate (Gap G-05) — periodic document review with automated due-date reminders and overdue tracking.",
    "detail": "<p>Periodic review: each document has review frequency (annual for most, semi-annual for critical safety). Review due date tracked. Power Automate sends reminders at 30, 7, and 0 days before due. Owner reviews → current (no change) or revises → re-approval. Overdue reviews visible on quality manager dashboard.</p>"},
"QAC-004": {"code": "S", "summary": "Standard D365 Quality Management — non-conformance management with root cause analysis, CAPA, and disposition workflow.",
    "detail": "<p>D365 <strong>Non-Conformance Management</strong>: NCR creation from any source (inspection failure, complaint, audit finding, process deviation) with description, affected product/batch, severity. Investigation: root cause analysis (Ishikawa, 5-Why). Disposition: use as-is, rework, regrade, scrap, return. CAPA: corrective/preventive actions with owner, deadline, effectiveness review. Trend analysis in Power BI.</p>"},
"QAC-005": {"code": "S", "summary": "Standard D365 Quality Management — CAPA management linked to NCRs, complaints, and audits with tracking and effectiveness verification.",
    "detail": "<p>CAPA management: corrective and preventive actions linked to: non-conformances, customer complaints, audit findings, or proactive improvements. Action tracking: description, responsible person, due date, completion status, and effectiveness verification (did the action prevent recurrence?). CAPA completion rate KPI in Power BI.</p>"},
"QAC-006": {"code": "C", "summary": "D365 Quality Management — internal audit planning, scheduling, execution, checklist management, and findings tracking.",
    "detail": "<p>Internal audit management: annual audit schedule (quality, food safety, environmental, HSE). Auditor assignments, checklists per audit type. Findings recorded as D365 non-conformances with severity. CAPA assigned from findings. Audit reports generated. Management review input compiled.</p>"},
"QAC-007": {"code": "C", "summary": "D365 Quality Management — external audit tracking with certification body, findings, corrective actions, and closure status.",
    "detail": "<p>External audit tracking: audit events recorded with: certification body, audit type (surveillance, recertification), date, findings (major NC, minor NC, observations), corrective action deadlines, and closure status. Certificate validity and renewal dates tracked with alerts.</p>"},
"QAC-008": {"code": "C", "summary": "D365 Quality Management + Power Automate — formal change management for recipes, processes, equipment, and suppliers.",
    "detail": "<p>Change management: change request → impact assessment → approval → implementation → verification. Covers: recipe changes, process changes, equipment changes, supplier changes. Change record: description, reason, risk assessment, approval chain, implementation steps, and verification that change achieved intended outcome.</p>"},
"QAC-009": {"code": "S", "summary": "Standard D365 Quality Management — customer complaint registration with investigation, root cause, resolution, and trend analysis.",
    "detail": "<p>Customer complaint management: complaint registered with: product, batch, customer, issue description, photos/evidence. Investigation linked to D365 quality non-conformance and batch trace. Root cause analysis documented. Resolution: credit note, replacement, price adjustment, or rejection with documented reason. Trend analysis in Power BI by type, customer, product, period.</p>"},
"QAC-010": {"code": "S", "summary": "Standard D365 Quality Management — supplier non-conformance tracking linked to incoming inspection and vendor evaluation.",
    "detail": "<p>Supplier NCR: quality issues on incoming materials recorded as non-conformances linked to the vendor and PO. NC data feeds vendor evaluation scoring. Trends tracked per vendor. Vendor notification and corrective action request process.</p>"},

# ═══════════════════════════════════════════════════════════════
#  9.2  FOOD SAFETY & HACCP  (QAC-011 → QAC-017)
# ═══════════════════════════════════════════════════════════════
"QAC-011": {"code": "C", "summary": "D365 Quality + SharePoint (Gap G-08) — HACCP plan documentation with hazard analysis, CCP definitions, and version control.",
    "detail": "<p>HACCP plan management: <strong>SharePoint</strong> stores HACCP plan documents (hazard analysis, CCP decision tree, flow diagrams) with version control. <strong>D365 Quality</strong> operationalises CCPs as quality test groups with critical limits, monitoring procedures, corrective actions. Plan revisions trigger D365 quality test configuration review.</p>"},
"QAC-012": {"code": "S", "summary": "Standard D365 Quality Management — CCP monitoring with real-time recording from equipment and manual checks with deviation alerts.",
    "detail": "<p>CCP monitoring: each CCP as quality test group with parameters, critical limits, frequency. Automated recording from sensors/equipment where integrated. Manual recording via production floor terminals. Deviation from critical limits triggers: immediate alert, production hold, corrective action, mandatory NCR.</p>"},
"QAC-013": {"code": "S", "summary": "Standard D365 Quality Management + Power Automate — automated CCP deviation alerts with mandatory corrective action and sign-off.",
    "detail": "<p>CCP deviation alerts: when monitoring values exceed critical limits, Power Automate triggers immediate notification to line supervisor + quality manager. Production hold on affected product. Corrective action procedure initiated per HACCP plan. Mandatory resolution and sign-off before production continues. All events documented.</p>"},
"QAC-014": {"code": "C", "summary": "D365 Quality Management + SharePoint — prerequisite program tracking: pest control, cleaning, hygiene, maintenance, water testing.",
    "detail": "<p>PRP management: SharePoint for PRP documentation (procedures, schedules). D365 Quality for operational checks: sanitation verification (swab tests), pest monitoring (trap inspections), personal hygiene audits, facility maintenance checks, water quality testing. Scheduled as recurring quality orders.</p>"},
"QAC-015": {"code": "C", "summary": "D365 product attributes + Quality — allergen management with register, cross-contamination risk, label verification, and cleaning validation.",
    "detail": "<p>Allergen management: allergen register per ingredient in D365 product master. BOM roll-up determines finished product allergens. Cross-contamination risk assessment documented. Allergen cleaning verification recorded as quality test results. Label content validation against allergen data (PRC-019/024).</p>"},
"QAC-016": {"code": "C", "summary": "D365 Quality Management — environmental monitoring program with sampling points, schedules, results, trending, and corrective actions.",
    "detail": "<p>Environmental monitoring: sampling points defined (surfaces, drains, air, water) with scheduled frequency. Test results (Listeria, Salmonella, TVC swabs, ATP) recorded in D365 quality orders. Trend analysis in Power BI. Positive findings trigger intensive sampling and sanitation corrective action.</p>"},
"QAC-017": {"code": "C", "summary": "D365 Quality Management — water quality monitoring: sampling schedule, test results, compliance tracking, and corrective actions.",
    "detail": "<p>Water quality: potable and process water testing at scheduled frequency. Results (microbiological, chemical) recorded in D365 quality. Compliance against standards tracked. Deviations trigger corrective action. Reports available for regulatory inspections.</p>"},

# ═══════════════════════════════════════════════════════════════
#  9.3  LABORATORY & TESTING  (QAC-018 → QAC-022)
# ═══════════════════════════════════════════════════════════════
"QAC-018": {"code": "C", "summary": "D365 Quality Management + LIMS — bidirectional LabWare LIMS integration for sample requests and test result receipt.",
    "detail": "<p>LIMS integration: D365 sends sample requests to LabWare LIMS (sample type, tests, batch reference). LabWare returns test results to D365 quality orders. Results linked to production batches. Integration via Azure Service Bus or file-based exchange. Turnaround tracking.</p>"},
"QAC-019": {"code": "S", "summary": "Standard D365 Quality Management — in-house test recording for temperature, visual, sensory, and other non-LIMS tests.",
    "detail": "<p>In-house testing: D365 quality test groups for tests outside LIMS: temperature checks, visual inspections, sensory panels, weight verification. Results entered in quality orders with: test type, value, specification limits, pass/fail. Trend analysis available.</p>"},
"QAC-020": {"code": "S", "summary": "Standard D365 Quality Management — specification management for raw materials, finished products, packaging, and ingredients.",
    "detail": "<p>Quality specifications: defined per material type with acceptable ranges for all tested parameters: chemical limits (histamine, dioxins, drug residues), microbiological limits (Listeria, Salmonella, TVC), physical criteria (colour, texture). Customer-specific specs where stricter. Centrally maintained and auto-applied.</p>"},
"QAC-021": {"code": "C", "summary": "D365 Quality Management — Certificate of Analysis (CoA) generation from test results per batch/shipment for customers.",
    "detail": "<p>CoA generation: from completed quality test results per batch. Customer-specific templates (some want full micro panel, others specific params). Attached to shipment documentation. Digital signature by authorised quality personnel.</p>"},
"QAC-022": {"code": "C", "summary": "D365 Quality Management — shelf-life study management with protocols, time-point testing, results, and validated shelf-life.",
    "detail": "<p>Shelf-life studies: study protocols managed in D365 with: product, packaging, test regime (time points, parameters), storage conditions. Results recorded at each time point. Validated shelf-life determination from study data. Results feed product shelf-life configuration.</p>"},

# ═══════════════════════════════════════════════════════════════
#  9.4  TRACEABILITY & RECALL  (QAC-023 → QAC-028)
# ═══════════════════════════════════════════════════════════════
"QAC-023": {"code": "S", "summary": "Standard D365 batch tracing — full chain traceability from egg/smolt through farming, processing, to dispatched product.",
    "detail": "<p>End-to-end traceability: D365 batch trace + AquaMonitor: egg supplier → smolt facility → vaccination → sea site/pen → feed batches → treatments → harvest → processing intake → production batch → product lot → customer shipment. Complete chain queryable from any point.</p>"},
"QAC-024": {"code": "S", "summary": "Standard D365 batch tracing — one-up-one-down traceability per EU Regulation 178/2002 (General Food Law).",
    "detail": "<p>One-up-one-down per EU Reg 178/2002: from every product, NordHav can identify supplier (one-up: raw material source) and customer (one-down: delivery recipient). NordHav's implementation significantly exceeds this minimum with full internal chain traceability.</p>"},
"QAC-025": {"code": "S", "summary": "Standard D365 batch trace inquiry — traceability query tool showing full upstream/downstream chain from any batch/lot number.",
    "detail": "<p>Traceability query: given any batch or lot number, D365 batch trace displays the full chain (upstream and downstream) with links to all records: health data, feed, treatments, quality tests, production parameters, customer deliveries.</p>"},
"QAC-026": {"code": "C", "summary": "D365 batch trace + Power Automate — mock recall exercises completing full trace within 4 hours (BRC requirement).",
    "detail": "<p>Mock recall: given a triggering event, D365 batch trace identifies all affected product within 4 hours (BRC/IFS requirement). Scope: affected batches, customer list, volumes, current inventory. Regular drill (minimum annual) with timed execution documented for audit evidence.</p>"},
"QAC-027": {"code": "C", "summary": "D365 + Power Automate — full recall management: scope identification, customer notification, product recovery, and regulatory reporting.",
    "detail": "<p>Recall management: recall decision with documented reason, scope, severity (Class I/II/III). D365 batch trace defines scope: products, batches, distribution (customers, quantities). Customer notifications generated. Return tracking via D365 returns with quarantine. Regulatory reporting to Mattilsynet. RASFF notification data if cross-border.</p>"},
"QAC-028": {"code": "S", "summary": "Standard D365 Quality Management — product withdrawal register with reason, scope, actions, and regulatory notifications.",
    "detail": "<p>Withdrawal register: all product withdrawals and recalls logged with: reason, scope (batches, volumes, customers), actions taken, regulatory notifications sent, and outcome. Register maintained for audit review and regulatory inspection.</p>"},

# ═══════════════════════════════════════════════════════════════
#  9.5  REGULATORY & ENVIRONMENTAL  (QAC-029 → QAC-034)
# ═══════════════════════════════════════════════════════════════
"QAC-029": {"code": "C", "summary": "SharePoint — regulatory reference library with applicable regulations, key requirements, applicability, and review schedule.",
    "detail": "<p>Regulatory library: SharePoint library of applicable regulations and standards with: reference number, title, applicability (sites/processes), key requirements summary, review schedule. Linked to QMS procedures that implement each requirement.</p>"},
"QAC-030": {"code": "C", "summary": "D365 + Power Automate — compliance task management with regulatory deadlines, certification renewals, and inspection schedules.",
    "detail": "<p>Compliance tasks: regulatory reporting dates, certification renewals, equipment inspections, and monitoring schedules tracked with: due dates, responsible person, and completion status. Power Automate reminders before deadlines. Compliance calendar dashboard in Power BI.</p>"},
"QAC-031": {"code": "C", "summary": "Microsoft Sustainability Manager + D365 + Power BI — full Scope 1/2/3 carbon accounting, energy, water, and waste KPIs for GRI/CSRD/ESRS.",
    "detail": "<p><strong>Microsoft Sustainability Manager</strong> is the central platform for environmental KPI tracking, ingesting activity data from D365 F&amp;O and AquaMonitor:</p><ul><li><strong>Scope 1</strong>: direct emissions from fuel consumption (sea transport, feed barges, vehicles) — sourced from D365 AP fuel invoices</li><li><strong>Scope 2</strong>: purchased electricity — sourced from D365 AP utility invoices, mapped to Norwegian grid emission factors</li><li><strong>Scope 3</strong>: upstream supply chain (feed production, logistics, packaging) — sourced from D365 procurement + supplier declarations</li><li><strong>Energy &amp; water</strong>: consumption per facility tracked via D365 invoice data and meter readings</li><li><strong>Waste &amp; recycling</strong>: waste generation by type with recycling rates from D365 inventory journals</li><li><strong>Emission factor libraries</strong>: Norwegian electricity grid factors, maritime transport, aquaculture-specific factors pre-loaded</li><li><strong>CSRD/ESRS reporting</strong>: data model aligned to EU Corporate Sustainability Reporting Directive and European Sustainability Reporting Standards</li><li><strong>Power BI dashboards</strong>: Sustainability Manager connector feeds ESG dashboards — GHG intensity per kg salmon, energy use trends, ASC indicator data</li></ul>"},
"QAC-032": {"code": "C", "summary": "D365 Inventory + SharePoint — chemical register with SDS links, hazard classification, approved use, storage, and quantities.",
    "detail": "<p>Chemical register: all chemicals (cleaning, water treatment, fish treatment, processing) in D365 inventory with: SDS document in SharePoint, hazard classification, approved use, storage requirements, quantities on-site. Accessible to all workers.</p>"},
"QAC-033": {"code": "C", "summary": "D365 Inventory + Microsoft Sustainability Manager + Power BI — waste tracking by type, quantity, disposal, hauler, and manifests with ESG roll-up.",
    "detail": "<p>Waste management in D365 Inventory: waste by type (organic, packaging, hazardous, general), quantity, disposal method, waste hauler, and manifests. Waste data flows to <strong>Microsoft Sustainability Manager</strong> via Azure Data Factory for inclusion in CSRD/ESRS environmental reporting — waste generation intensity, recycling rates, and circular economy metrics. Power BI dashboards combine operational waste data with ESG targets.</p>"},
"QAC-034": {"code": "C", "summary": "D365 + AquaMonitor + Microsoft Sustainability Manager + Power BI — ASC/certification data aggregation across environmental, social, feed, and traceability indicators.",
    "detail": "<p>ASC certification data: environmental indicators (lice, treatments, escapes, MOM results from AquaMonitor), social (worker safety, training from D365 HR), feed sustainability (FFDR, sourcing certifications from AquaMonitor), traceability (D365 batch trace). <strong>Microsoft Sustainability Manager</strong> aggregates carbon footprint and environmental metrics alongside ASC-specific indicators, enabling a single reporting view. Power BI compiles all indicators for efficient annual audit preparation and continuous certification readiness monitoring.</p>"},

# ═══════════════════════════════════════════════════════════════
#  9.6  HSE  (QAC-035 → QAC-040)
# ═══════════════════════════════════════════════════════════════
"QAC-035": {"code": "C", "summary": "D365 or Power Apps — HSE incident reporting with classification, immediate actions, and investigation per Norwegian AML.",
    "detail": "<p>Incident reporting: via D365 or Power Apps form: type (injury, near-miss, hazardous observation, environmental), date/time/location, affected person(s), severity, description, immediate actions. Serious injuries reported to Arbeidstilsynet per AML. Status workflow: Reported → Investigating → Actions → Closed.</p>"},
"QAC-036": {"code": "C", "summary": "D365 Quality Management — structured incident investigation with root cause analysis, corrective actions, and verification.",
    "detail": "<p>Incident investigation: root cause analysis (5-Why, fishbone), contributing factors, witness statements, corrective/preventive actions assigned with owner, deadline, and verification of effectiveness.</p>"},
"QAC-037": {"code": "C", "summary": "D365 + Power BI — risk assessment register with hazard identification, scoring, controls, residual risk, and review schedule.",
    "detail": "<p>Risk assessments: per facility/department/activity with hazard description, risk score (probability × consequence), existing controls, residual risk, additional controls needed, responsible person, review date. Power BI heat maps, high-priority risks, control status.</p>"},
"QAC-038": {"code": "C", "summary": "D365 + Power BI — HSE KPIs: LTIFR, TRIR, sick leave %, near-miss rate, days since last LTI.",
    "detail": "<p>HSE statistics: Lost Time Injury Frequency Rate (LTIFR), Total Recordable Injury Rate (TRIR), near-miss reporting rate, sick leave %, days since last LTI. Trending by type, location, period. Benchmarks against industry and targets.</p>"},
"QAC-039": {"code": "C", "summary": "SharePoint + D365 Inventory — SDS library accessible at all locations linked to chemical register.",
    "detail": "<p>SDS management: Safety Data Sheets in SharePoint per chemical, linked to D365 chemical register (QAC-032). Accessible to all workers at applicable locations. Current SDS ensured via review workflow.</p>"},
"QAC-040": {"code": "C", "summary": "D365 HR + Asset Management — PPE issuance tracking per employee with type, date, replacement schedule, and certification status.",
    "detail": "<p>PPE management: PPE types tracked per employee in D365 HR: issue date, replacement schedule, certification/inspection status (fall protection, harness testing). Replacement alerts via Power Automate. PPE inventory managed via D365.</p>"},
}
