"""Solution response data — Processing & Value-Added Products (PRC-001 → PRC-067)"""

SOLUTIONS_PRC = {
# ═══════════════════════════════════════════════════════════════
#  7.1  HARVEST RECEPTION & LIVE FISH HANDLING  (PRC-001 → PRC-004)
# ═══════════════════════════════════════════════════════════════
"PRC-001": {"code": "C", "summary": "D365 SCM production orders + AquaMonitor — well-boat arrival recording with origin, count, weight, and welfare data.",
    "detail": "<p>Well-boat reception managed through <strong>D365 Production Control</strong> + AquaMonitor:</p><ul><li><strong>Intake recording</strong>: well-boat ID, arrival time, origin site/pen(s), declared fish count, estimated live weight, water quality during transport, welfare observations</li><li><strong>AquaMonitor link</strong>: harvest execution record linked to D365 production order via generation batch ID — farm-to-factory traceability chain established</li><li><strong>Quality acceptance</strong>: pre-slaughter quality check (welfare assessment, temperature, starvation period verification) recorded against the incoming batch</li></ul>"},
"PRC-002": {"code": "C", "summary": "D365 Advanced Warehousing — holding tank tracking with fish count, water temperature, O₂, and planned slaughter time.",
    "detail": "<p>Holding tank management via D365 <strong>Advanced Warehousing</strong> location tracking:</p><ul><li><strong>Tank locations</strong>: each holding tank modeled as a warehouse location. Tracked per tank: fish count, live weight, holding start time, assigned slaughter slot</li><li><strong>Environmental monitoring</strong>: water temperature and O₂ via IoT sensors → Azure IoT Hub → alerts on exceedance</li><li><strong>Planned slaughter time</strong>: each batch assigned planned start based on resting period, line capacity, and schedule</li><li><strong>Capacity</strong>: total tank capacity tracked to prevent over-reception</li></ul>"},
"PRC-003": {"code": "C", "summary": "D365 batch attributes + Power Automate — resting period tracking with time alerts for minimum (4h), maximum (24h), and quality risk.",
    "detail": "<p>Resting period management:</p><ul><li><strong>Timer</strong>: holding start time as batch attribute. Duration calculated real-time</li><li><strong>Alerts</strong>: notification at 4 hours (ready), warning at 12 hours (prioritise), critical at 24 hours (quality risk). Environmental deterioration alerts independent of time</li><li><strong>Dashboard</strong>: all tanks with batch, fish count, resting duration (color-coded), and water parameters</li></ul>"},
"PRC-004": {"code": "S", "summary": "Standard D365 batch tracking — farm-to-factory traceability linking reception batch to origin site, pen, generation, feed, and treatments.",
    "detail": "<p>D365 <strong>batch tracking</strong> establishes the critical traceability handover:</p><ul><li><strong>Batch creation</strong>: processing batch linked to AquaMonitor generation ID. Stores: origin site, pen(s), generation, harvest date, quality grade</li><li><strong>Upstream traceability</strong>: via generation ID — feed batches, treatments, vaccinations, lice history, water quality, growth data all traceable</li><li><strong>Batch attributes</strong>: origin site, species, generation, quality grade, regulatory data (withdrawal period confirmation)</li></ul>"},

# ═══════════════════════════════════════════════════════════════
#  7.2  SLAUGHTER & PRIMARY PROCESSING  (PRC-005 → PRC-017)
# ═══════════════════════════════════════════════════════════════
"PRC-005": {"code": "S", "summary": "Standard D365 Production Control — production order management with planned volume, specs, customer allocations, and line assignment.",
    "detail": "<p>D365 <strong>Production Control</strong>:</p><ul><li><strong>Production order</strong>: planned volume, product specs, customer allocations, production date, assigned line</li><li><strong>BOM</strong>: input (live fish) → outputs (HOG, by-products). Versions per species/type</li><li><strong>Route</strong>: stunning → bleeding → gutting → grading → washing → chilling with standard times</li><li><strong>Lifecycle</strong>: Created → Estimated → Scheduled → Released → Started → Finished → Ended</li></ul>"},
"PRC-006": {"code": "S", "summary": "Standard D365 Production Control — daily/weekly scheduling considering raw material, orders, line capacity, staff, and product mix.",
    "detail": "<p>D365 production scheduling:</p><ul><li><strong>Weekly</strong>: harvest volumes (AquaMonitor) + customer demand → schedule per product/line/shift</li><li><strong>Daily</strong>: shift schedules with line assignments, crew, material staging, target throughput</li><li><strong>Capacity</strong>: line capacity in resource groups. Finite capacity scheduling</li><li><strong>Material</strong>: consumable requirements via MRP from production schedule</li></ul>"},
"PRC-007": {"code": "C", "summary": "D365 production BOM + route with slaughter line integration — stunning method, parameters, welfare compliance recording.",
    "detail": "<p>Stunning &amp; slaughter recording:</p><ul><li><strong>Route</strong>: stunning/slaughter as operations with method (electrical/percussive), voltage, duration, welfare criteria</li><li><strong>Equipment integration</strong>: automation systems push data via Azure Service Bus: throughput, stunning parameters, equipment status</li><li><strong>Welfare</strong>: stunning effectiveness checks per batch. Deviations trigger non-conformance</li><li><strong>Record</strong>: date, time, batch, fish count, method/parameters, responsible operator</li></ul>"},
"PRC-008": {"code": "S", "summary": "Standard D365 catch-weight — individual fish HOG weight capture from in-line conveyor scales with batch aggregation.",
    "detail": "<p>D365 <strong>catch-weight</strong>:</p><ul><li><strong>Capture</strong>: conveyor scales weigh each fish (HOG) → D365 catch-weight registrations</li><li><strong>Aggregation</strong>: individual weights → batch totals: total HOG weight, count, average</li><li><strong>Distribution</strong>: statistical analysis (mean, std dev, size classes) for pack planning</li></ul>"},
"PRC-009": {"code": "C", "summary": "D365 batch attributes + grading equipment — automated quality grade, weight class, and colour grade capture from sorting machines.",
    "detail": "<p>Automatic grading data:</p><ul><li><strong>Integration</strong>: grading machines classify each fish by weight class, quality grade (Superior/Ordinary/Production), colour (SalmoFan). Results to D365</li><li><strong>Batch attributes</strong>: grade distribution stored: % Superior, % Ordinary, average SalmoFan, weight class breakdown</li><li><strong>Routing</strong>: fish routed to appropriate lines based on grade</li><li><strong>Analytics</strong>: Power BI grade trends per site, generation, season</li></ul>"},
"PRC-010": {"code": "S", "summary": "Standard D365 co-product/by-product — yield tracking at each step with percentage calculations and variance against BOM standards.",
    "detail": "<p>Yield tracking:</p><ul><li><strong>Step yields</strong>: live → bled → HOG → fillet → trimmed → portions. Each % tracked vs. standard</li><li><strong>BOM</strong>: standard yields (gutting 87%, filleting 55%). Variance analysis</li><li><strong>Losses</strong>: per step in kg and %: head, viscera, blood, trim, frames, skin, waste</li><li><strong>Reporting</strong>: variance per batch, shift, line, period</li></ul>"},
"PRC-011": {"code": "S", "summary": "Standard D365 batch management — production batch definition with configurable lot numbering and GS1-compliant structure.",
    "detail": "<p>Batch definition:</p><ul><li><strong>Rule</strong>: one batch = one day's processing from one origin site (configurable). GS1-compliant number sequence</li><li><strong>Attributes</strong>: production date, origin, species, grade distribution, best-before date</li><li><strong>Split/merge</strong>: parent-child traceability maintained when batches split or merge</li></ul>"},
"PRC-012": {"code": "S", "summary": "Standard D365 catch-weight — full dual-unit tracking (count + actual weight) for variable-weight fish products.",
    "detail": "<p>Catch-weight / variable weight:</p><ul><li><strong>Dual-unit</strong>: nominal (count) and actual (kg). Each piece has unique weight</li><li><strong>Capture points</strong>: intake, post-gutting, grading, packing, dispatch</li><li><strong>Financial</strong>: invoicing and costing use actual catch-weight</li><li><strong>Orders</strong>: orders in kg with fulfilment based on available catch-weight</li></ul>"},
"PRC-013": {"code": "S", "summary": "Standard D365 production multi-level BOM — filleting line with input/output tracking, yield per line, and quality metrics.",
    "detail": "<p>Filleting management:</p><ul><li><strong>BOM</strong>: input HOG → outputs: fillets (skin-on/off, trimmed), trim, by-products (frames, skin)</li><li><strong>Yield</strong>: fillet yield per batch, by line, operator, shift, input quality grade</li><li><strong>Quality</strong>: colour (SalmoFan), trim level, fat %, defect incidence</li><li><strong>Catch-weight</strong>: each fillet weighed for sorting and accurate yield</li></ul>"},
"PRC-014": {"code": "C", "summary": "D365 Quality Management — pin bone removal recording with X-ray/manual inspection pass rates and non-conformance tracking.",
    "detail": "<p>Pin bone tracking:</p><ul><li><strong>Removal</strong>: recorded as production operation per batch. Method (machine/manual) tracked</li><li><strong>Inspection</strong>: X-ray or manual samples. Pass/fail rate per batch and line</li><li><strong>Quality orders</strong>: triggered at pin-bone stage with sampling plans</li><li><strong>NCR</strong>: pin bone detection in finished product triggers root cause investigation</li></ul>"},
"PRC-015": {"code": "S", "summary": "Standard D365 co-product/by-product — all by-product streams tracked by type and volume per batch with cost/revenue allocation.",
    "detail": "<p>By-product tracking:</p><ul><li><strong>Streams</strong>: heads, frames, belly trim, skins, viscera, blood water — each as BOM output</li><li><strong>Recording</strong>: kg per type per batch via production reporting</li><li><strong>Cost</strong>: allocated between primary and by-products (NRV, weight, fixed %)</li><li><strong>Revenue</strong>: by-product sales tracked with revenue credit against processing cost</li></ul>"},
"PRC-016": {"code": "C", "summary": "D365 Inventory Management — ensilage tracking with input volumes, acid addition, tank levels, and dispatch to buyers.",
    "detail": "<p>Ensilage management:</p><ul><li><strong>Input</strong>: waste volumes directed to ensilage via inventory journals</li><li><strong>Production</strong>: acid addition (type, quantity), date/time, temperature</li><li><strong>Tanks</strong>: levels as inventory by location. Capacity alerts</li><li><strong>Dispatch</strong>: collection recorded as D365 sales with volume and documentation</li></ul>"},
"PRC-017": {"code": "C", "summary": "D365 Inventory Management — ice plant production, consumption tracking per batch, and capacity monitoring.",
    "detail": "<p>Ice management:</p><ul><li><strong>Production</strong>: daily output tracked as manufactured item</li><li><strong>Consumption</strong>: per batch via BOM consumption on production orders</li><li><strong>Capacity</strong>: plant capacity vs. demand; alerts when behind</li><li><strong>Quality</strong>: maintenance via Asset Management. Microbiological checks via quality orders</li></ul>"},

# ═══════════════════════════════════════════════════════════════
#  7.3  PACKING & LABELING  (PRC-018 → PRC-025)
# ═══════════════════════════════════════════════════════════════
"PRC-018": {"code": "S", "summary": "Standard D365 BOM — packing specification library per customer/product with box type, liner, ice, label, tolerances.",
    "detail": "<p>Packing specs via D365 BOM variants:</p><ul><li><strong>BOMs</strong>: per product: box type (EPS, cardboard), size, ice, liner, label, auxiliaries. Versions per market/customer</li><li><strong>Customer-specific</strong>: branding, sizes, label content as BOM versions</li><li><strong>Tolerances</strong>: target fill weight with min/max per specification</li><li><strong>Instructions</strong>: customer packing instructions as document attachments</li></ul>"},
"PRC-019": {"code": "C", "summary": "D365 label printing integration — automated label generation with regulatory fields, barcodes, batch data, and multi-language text.",
    "detail": "<p>Label generation:</p><ul><li><strong>Content</strong>: product name (common + Latin), species, production method, origin, FAO area, weight, dates, batch, producer ID, GS1-128 barcode, allergens, nutrition</li><li><strong>Templates</strong>: per market (EU, UK, USA, Asia), customer, product, language</li><li><strong>Integration</strong>: D365 → label printer (Marel Innova, NiceLabel) for automated in-line printing</li><li><strong>GS1</strong>: barcode with GTIN, batch, production date, best-before, net weight</li></ul>"},
"PRC-020": {"code": "C", "summary": "D365 product translations + label system — multi-language label text in 10+ languages with market-specific regulatory content.",
    "detail": "<p>Multi-language labels:</p><ul><li><strong>Translations</strong>: product descriptions in 10+ languages: NO, EN, FR, DE, ES, IT, NL, PL, JA, ZH</li><li><strong>Selection</strong>: template selected by sales order destination market</li><li><strong>Regulatory</strong>: market-specific text per destination requirements</li><li><strong>Allergens</strong>: localised per language per EU Reg 1169/2011</li></ul>"},
"PRC-021": {"code": "S", "summary": "Standard D365 product data — full GS1 compliance with GTIN, SSCC, GS1-128, and GS1 DataMatrix codes.",
    "detail": "<p>GS1 compliance:</p><ul><li><strong>GTIN</strong>: per product variant in product master</li><li><strong>SSCC</strong>: per pallet (license plate) per GS1 standards</li><li><strong>GS1-128</strong>: GTIN, batch, production date, best-before, net weight, SSCC</li><li><strong>DataMatrix</strong>: 2D codes where customers require compact format</li><li><strong>Digital Link</strong>: future capability for consumer QR codes</li></ul>"},
"PRC-022": {"code": "S", "summary": "Standard D365 catch-weight — individual item weight aggregation into case net weight with piece count and average.",
    "detail": "<p>Case weight aggregation:</p><ul><li><strong>Item weights</strong>: each fish/fillet weighed on packing line scales</li><li><strong>Aggregation</strong>: D365 sums into case net weight, records piece count, average</li><li><strong>Label</strong>: actual net weight, piece count, product, batch, GS1-128 barcode</li><li><strong>Tolerance</strong>: validated against target ± tolerance; failures flagged</li></ul>"},
"PRC-023": {"code": "S", "summary": "Standard D365 license plate / pallet management — SSCC pallet label with product, case count, weight, and delivery info.",
    "detail": "<p>Pallet management:</p><ul><li><strong>Building</strong>: boxes assigned to pallets (license plates) with unique SSCC</li><li><strong>Label</strong>: SSCC barcode, product, case count, total weight, production date, best-before, delivery</li><li><strong>Traceability</strong>: pallet → boxes → batch → intake → farm generation</li><li><strong>Inventory</strong>: WMS tracks at license-plate level in cold storage and dispatch</li></ul>"},
"PRC-024": {"code": "C", "summary": "D365 Quality Management + vision system — automated label verification for presence, barcode readability, and content correctness.",
    "detail": "<p>Label verification:</p><ul><li><strong>Vision system</strong>: checks every label: presence, barcode grade, correct GTIN, date, language</li><li><strong>D365 integration</strong>: results as quality test results. Failures trigger line stop, re-label, quality event</li><li><strong>CCP</strong>: allergen labeling results maintained as CCP records where applicable</li><li><strong>Statistics</strong>: reject rate per shift/line/product in Power BI</li></ul>"},
"PRC-025": {"code": "C", "summary": "D365 Quality Management — average weight (e-mark) compliance per EU Directive 76/211/EEC with TU1/TU2 tolerance checks.",
    "detail": "<p>Average weight compliance:</p><ul><li><strong>Sampling</strong>: per production run per EU Directive and Norwegian regulations</li><li><strong>TU1/TU2</strong>: individual tolerance and maximum deficiency validated per nominal weight</li><li><strong>Recording</strong>: checkweigher data or samples. Statistical analysis for compliance</li><li><strong>Reports</strong>: e-mark compliance reports per run — audit-ready</li></ul>"},

# ═══════════════════════════════════════════════════════════════
#  7.4  FREEZING & COLD STORAGE  (PRC-026 → PRC-030)
# ═══════════════════════════════════════════════════════════════
"PRC-026": {"code": "S", "summary": "Standard D365 production scheduling — freeze scheduling by product type, order, and IQF/blast/plate freezer capacity.",
    "detail": "<p>Freeze scheduling:</p><ul><li><strong>Freezer types</strong>: IQF tunnel, blast, plate — each as D365 resource with capacity</li><li><strong>Scheduling</strong>: assigned by product type, customer needs, freezer availability</li><li><strong>Operation</strong>: freezing as route operation with target core temperature and duration</li><li><strong>Queue</strong>: products queued for freezing tracked in WMS — FIFO</li></ul>"},
"PRC-027": {"code": "S", "summary": "Standard D365 production recording — freezing parameters per batch: freezer unit, start/end, core temperature, verification.",
    "detail": "<p>Freezing records:</p><ul><li><strong>Parameters</strong>: product/batch, freezer unit, load/unload time, target/achieved core temp, duration</li><li><strong>Verification</strong>: core temperature by probe — D365 quality test result (must reach -18°C)</li><li><strong>Automated</strong>: where freezer systems support export, cycle data logged automatically</li><li><strong>HACCP</strong>: records evidence product achieved required core temperature</li></ul>"},
"PRC-028": {"code": "S", "summary": "Standard D365 WMS — cold store location management with row/stack/level, temperature zones, and product tracking.",
    "detail": "<p>Cold store warehouse management:</p><ul><li><strong>Locations</strong>: zone (chilled, frozen, deep freeze), aisle, rack, level. Capacity tracked</li><li><strong>Product</strong>: every pallet in its location with: product, batch, qty, weight, date, allocated order</li><li><strong>Putaway</strong>: WMS directives for optimal location by temp zone, product, capacity</li><li><strong>Mobile</strong>: D365 Warehouse app — scan pallet, scan location for all operations</li></ul>"},
"PRC-029": {"code": "S", "summary": "Standard D365 batch attributes — storage duration tracking with shelf-life alerts and FEFO picking logic.",
    "detail": "<p>Storage duration / shelf-life:</p><ul><li><strong>Tracking</strong>: best-before from production date + shelf-life days. Days in storage calculated</li><li><strong>FEFO</strong>: First Expired First Out enforced for picking</li><li><strong>Alerts</strong>: approaching best-before flagged for priority sales, markdown, or disposal</li><li><strong>Block</strong>: expired product blocked from sale via inventory status rules</li></ul>"},
"PRC-030": {"code": "C", "summary": "D365 + IoT Hub — continuous temperature monitoring in cold stores/dispatch with deviation alerts and HACCP logging.",
    "detail": "<p>Temperature monitoring:</p><ul><li><strong>Sensors</strong>: in cold stores, freezers, dispatch areas → Azure IoT Hub</li><li><strong>Logging</strong>: every 5-15 minutes — unbroken HACCP records</li><li><strong>Alerts</strong>: deviations trigger immediate alerts. Excursions recorded as non-conformances</li><li><strong>Dashboard</strong>: Power BI real-time temperatures across zones with history</li></ul>"},

# ═══════════════════════════════════════════════════════════════
#  7.5  VALUE-ADDED PROCESSING (VAP)  (PRC-031 → PRC-045)
# ═══════════════════════════════════════════════════════════════
"PRC-031": {"code": "S", "summary": "Standard D365 Production BOM — recipe/BOM for VAP with ingredients, quantities, allergens, and processing instructions.",
    "detail": "<p>VAP recipe management:</p><ul><li><strong>Recipe BOM</strong>: salmon input, ingredients (salt, sugar, spices, smoke, marinades), packaging, processing aids</li><li><strong>Quantities</strong>: per batch size with configurable scaling</li><li><strong>Allergens</strong>: per ingredient; BOM roll-up determines finished product allergen profile</li><li><strong>Processing</strong>: route operations with parameters, durations, quality criteria</li></ul>"},
"PRC-032": {"code": "S", "summary": "Standard D365 BOM versioning — recipe version control with effective dates, change tracking, and approval workflow.",
    "detail": "<p>Recipe version control:</p><ul><li><strong>Versions</strong>: numbered, one active at a time per date range. Previous retained</li><li><strong>Tracking</strong>: what changed, when, who, why</li><li><strong>Approval</strong>: R&amp;D → quality → regulatory check → active</li><li><strong>Dates</strong>: from/to for planned recipe changes</li></ul>"},
"PRC-033": {"code": "S", "summary": "Standard D365 Production Control — VAP production orders with product, quantity, recipe version, scheduling, and material BOM.",
    "detail": "<p>VAP production orders:</p><ul><li><strong>Order</strong>: product, quantity, BOM version, batch size, date, line</li><li><strong>Materials</strong>: BOM explosion calculates requirements. Auto-reservation with shortage alerts</li><li><strong>Packaging</strong>: in BOM, consumed on completion</li><li><strong>Lifecycle</strong>: Created → Estimated → Scheduled → Released → Started → Finished → Ended</li></ul>"},
"PRC-034": {"code": "C", "summary": "D365 production reservation — raw material allocation from primary processing to VAP by quality, size, and priority.",
    "detail": "<p>Raw material allocation:</p><ul><li><strong>Allocation</strong>: fresh fillets allocated to VAP orders by quality, size, quantity, priority</li><li><strong>Reservation</strong>: reserved batches blocked from direct fresh sales</li><li><strong>Selection</strong>: by freshness, quality, customer spec match</li><li><strong>Shortage</strong>: insufficient supply triggers re-scheduling or frozen sourcing</li></ul>"},
"PRC-035": {"code": "S", "summary": "Standard D365 batch tracking — full ingredient lot traceability per VAP batch linking every input to finished product.",
    "detail": "<p>Ingredient lot traceability:</p><ul><li><strong>Recording</strong>: every lot consumed: salmon batch(es), salt, spice, smoke wood, marinade, packaging lots</li><li><strong>Scanning</strong>: operators scan ingredient lots against BOM lines</li><li><strong>Trace</strong>: finished product → all ingredients. Ingredient → all finished products</li><li><strong>Recall</strong>: contaminated ingredient → all affected VAP batches identified in minutes</li></ul>"},
"PRC-036": {"code": "C", "summary": "D365 production route + equipment — smoking process with kiln, temperature curves, wood type, duration, and yield.",
    "detail": "<p>Smoking process recording:</p><ul><li><strong>Route</strong>: kiln ID, target smoking curve, wood type, standard yield</li><li><strong>Parameters</strong>: product (kg), actual temps, wood type/qty, start/end, core temp</li><li><strong>Integration</strong>: kiln control data logged automatically where supported</li><li><strong>Yield</strong>: 75-85% tracked per batch vs. standard</li></ul>"},
"PRC-037": {"code": "C", "summary": "D365 production route — curing/marination with recipe, brine, injection rate, curing time, temperature, and yield.",
    "detail": "<p>Curing / marination recording:</p><ul><li><strong>Operation</strong>: recipe, concentration, injection rate, duration, temperature</li><li><strong>Batch</strong>: recipe, brine/cure batch, injection parameters, curing time, temperature, salt content</li><li><strong>Quality</strong>: salt, pH, weight gain/loss as quality test results</li><li><strong>Yield</strong>: weight change tracked for costing</li></ul>"},
"PRC-038": {"code": "C", "summary": "D365 production BOM + catch-weight — slicing operation with input, output, thickness, pack weights, yield, and waste.",
    "detail": "<p>Slicing line data:</p><ul><li><strong>Operation</strong>: input product/batch, target thickness, pack weight, standard yield</li><li><strong>Output</strong>: pack count, total kg, actual weights (checkweigher), yield, trim/waste</li><li><strong>Catch-weight</strong>: individual pack weights as catch-weight registrations</li><li><strong>Analysis</strong>: yield per input quality, operator, machine, blade age</li></ul>"},
"PRC-039": {"code": "C", "summary": "D365 production + equipment — thermoforming/MAP machine interface for pack count, gas mix, seal params, and rejects.",
    "detail": "<p>Packaging machine integration:</p><ul><li><strong>Data</strong>: pack count, gas mix (CO₂%, N₂%, O₂ residual), seal pressure/temperature, speed via middleware</li><li><strong>Quality</strong>: gas and seal results as D365 quality tests. Out-of-spec triggers investigation</li><li><strong>Rejects</strong>: counted and categorised by reason</li><li><strong>HACCP</strong>: MAP composition as food safety records</li></ul>"},
"PRC-040": {"code": "S", "summary": "Standard D365 Quality Management — metal detection/X-ray CCP with inspection counts, rejects, and calibration verification.",
    "detail": "<p>Metal detection / X-ray:</p><ul><li><strong>CCP</strong>: Critical Control Points with sensitivity limits, calibration frequency, corrective actions</li><li><strong>Results</strong>: packs inspected, rejects (count, reason), calibration pass/fail</li><li><strong>Calibration</strong>: start of shift, every 2 hours, end of shift recorded in D365</li><li><strong>Deviation</strong>: failure triggers line stop, quarantine, and non-conformance</li></ul>"},
"PRC-041": {"code": "C", "summary": "D365 catch-weight + quality — checkweigher integration for per-pack weight, statistical compliance, and reject tracking.",
    "detail": "<p>Checkweigher integration:</p><ul><li><strong>Capture</strong>: every pack weighed; data as catch-weight and quality results</li><li><strong>Tolerance</strong>: underweight/overweight packs rejected</li><li><strong>Compliance</strong>: statistical data for average weight per EU Directive (PRC-025)</li><li><strong>Rejects</strong>: counts per run; excessive triggers recalibration</li></ul>"},
"PRC-042": {"code": "S", "summary": "Standard D365 production yield — VAP yield analysis at each stage comparing actual vs. recipe standard with cost impact.",
    "detail": "<p>VAP yield analysis:</p><ul><li><strong>Stages</strong>: raw material → salted/cured → smoked → sliced → packed. Each actual vs. standard</li><li><strong>Variance</strong>: where loss occurred — smoking, slicing, packing</li><li><strong>Reporting</strong>: Power BI per product, recipe, line, operator, period</li><li><strong>Cost</strong>: yield variance in NOK — actual vs. standard cost</li></ul>"},
"PRC-043": {"code": "S", "summary": "Standard D365 co-product/by-product — VAP co-products (trimmings, off-cuts) and waste tracked with cost/revenue allocation.",
    "detail": "<p>Co-product &amp; waste:</p><ul><li><strong>Co-products</strong>: smoked trimmings, belly trim, off-cuts as separate output items</li><li><strong>Waste</strong>: packaging waste, non-recoverable trim, condemned product by type/volume</li><li><strong>Cost</strong>: joint cost allocated (NRV, weight, formula)</li><li><strong>Revenue</strong>: co-product sales tracked. Waste disposal costs recorded</li></ul>"},
"PRC-044": {"code": "S", "summary": "Standard D365 product master — full VAP catalogue (~120 SKUs) with recipe links, shelf life, nutrition, allergens, and customer variants.",
    "detail": "<p>VAP SKU management:</p><ul><li><strong>Catalogue</strong>: ~120 SKUs with code, description (multi-language), BOM link, packaging, lifecycle</li><li><strong>Dimensions</strong>: species, preparation, pack size, packaging type</li><li><strong>Regulatory</strong>: shelf life, storage conditions, nutrition, allergens, ingredients</li><li><strong>Variants</strong>: private label and custom sizes as BOM versions</li></ul>"},
"PRC-045": {"code": "S", "summary": "Standard D365 batch attributes — shelf-life management with auto-calculated best-before dates by product type and packaging.",
    "detail": "<p>Shelf-life management:</p><ul><li><strong>Rules</strong>: per product/packaging: fresh HOG 12-14d, vacuum fillet 14-18d, MAP 10-14d, IQF 18-24m, smoked vacuum 21-28d</li><li><strong>Auto-calculation</strong>: best-before from production date + shelf-life days</li><li><strong>Controls</strong>: FEFO picking, minimum remaining shelf-life at delivery</li><li><strong>Expired</strong>: automatically blocked from sale via inventory status</li></ul>"},

# ═══════════════════════════════════════════════════════════════
#  7.6  PRODUCTION EXECUTION  (PRC-046 → PRC-050)
# ═══════════════════════════════════════════════════════════════
"PRC-046": {"code": "S", "summary": "Standard D365 production floor execution — real-time line monitoring with throughput, downtime, speed, and utilisation.",
    "detail": "<p>Line monitoring:</p><ul><li><strong>Throughput</strong>: current rate (kg/hr, fish/hr, packs/hr) on floor monitors and D365 dashboard</li><li><strong>Downtime</strong>: active events flagged with duration and reason</li><li><strong>Speed</strong>: actual vs. target; deviations investigated</li><li><strong>Utilisation</strong>: running time ÷ available time per shift, trended</li></ul>"},
"PRC-047": {"code": "S", "summary": "Standard D365 production floor execution — downtime recording with line, time, reason codes (planned/unplanned), and impact.",
    "detail": "<p>Downtime recording:</p><ul><li><strong>Events</strong>: line/equipment, stop/restart time, duration, reason code</li><li><strong>Hierarchy</strong>: Planned (changeover, cleaning, break, maintenance) vs. Unplanned (breakdown, electrical, quality, no material)</li><li><strong>Impact</strong>: linked to production orders — planned vs. actual output</li><li><strong>Analysis</strong>: Power BI Pareto, planned/unplanned ratio, trend per line/shift</li></ul>"},
"PRC-048": {"code": "S", "summary": "Standard D365 + Power BI — OEE calculation per line (availability × performance × quality) by line, shift, and period.",
    "detail": "<p>OEE calculation:</p><ul><li><strong>Availability</strong>: actual running ÷ planned time</li><li><strong>Performance</strong>: actual throughput ÷ maximum theoretical</li><li><strong>Quality</strong>: good output ÷ total output</li><li><strong>OEE</strong> = A × P × Q per line per shift. Daily/weekly/monthly aggregation. Power BI trend, component breakdown, targets</li></ul>"},
"PRC-049": {"code": "S", "summary": "Standard D365 production reporting — shift reports with volumes, yield, quality, downtime, staffing, and handover notes.",
    "detail": "<p>Shift reporting:</p><ul><li><strong>Production</strong>: volumes by product, yield per shift</li><li><strong>Quality</strong>: inspection results, NCRs, CCP deviations, grade distribution</li><li><strong>Downtime</strong>: total, major events, reason breakdown</li><li><strong>Staffing</strong>: crew per line from Time &amp; Attendance</li><li><strong>Handover</strong>: supervisor notes for incoming shift</li></ul>"},
"PRC-050": {"code": "S", "summary": "Standard D365 production routes + Quality — CIP/cleaning schedules with procedure, chemical tracking, and verification.",
    "detail": "<p>Cleaning management:</p><ul><li><strong>Schedules</strong>: daily cleaning as route operations between shifts. CIP, foam, dry per equipment</li><li><strong>Recording</strong>: procedure, chemicals (lot-tracked), person, time, verification</li><li><strong>Verification</strong>: post-clean inspection as quality results: visual, ATP, swabs</li><li><strong>CIP</strong>: automated cycle data (temperature, flow, concentration, duration) logged</li></ul>"},

# ═══════════════════════════════════════════════════════════════
#  7.7  PROCESSING QUALITY  (PRC-051 → PRC-055)
# ═══════════════════════════════════════════════════════════════
"PRC-051": {"code": "S", "summary": "Standard D365 Quality Management — in-process quality checks at defined control points with sampling and pass/fail.",
    "detail": "<p>In-process quality:</p><ul><li><strong>Associations</strong>: auto quality orders at receipt, start, finish, packing</li><li><strong>Tests</strong>: temperature, weight, visual, colour, freshness, foreign body</li><li><strong>Sampling</strong>: statistical frequency per product and control point</li><li><strong>Results</strong>: production floor or mobile with auto non-conformance on failure</li></ul>"},
"PRC-052": {"code": "S", "summary": "Standard D365 Quality Management — quality hold/release workflow preventing dispatch until quality-approved.",
    "detail": "<p>Quality hold/release:</p><ul><li><strong>Hold</strong>: status 'Quality Inspection' — blocked from sales and shipping</li><li><strong>Release</strong>: quality reviews → release (Available) or reject (rework/regrade/scrap). Approval workflow</li><li><strong>Enforcement</strong>: D365 prevents dispatch of held product</li><li><strong>Audit</strong>: hold/release history with reason, duration, results, approver</li></ul>"},
"PRC-053": {"code": "S", "summary": "Standard D365 production — rework management with rework orders, batch tracking, downgrade, and cost allocation.",
    "detail": "<p>Rework management:</p><ul><li><strong>Rework order</strong>: input non-conforming batch → output reworked product</li><li><strong>Batch</strong>: new number or updated attributes. Full traceability maintained</li><li><strong>Cost</strong>: rework costs added to product cost, separately identifiable</li><li><strong>Regrade</strong>: downgrade tracked with reclassification and revaluation</li></ul>"},
"PRC-054": {"code": "C", "summary": "D365 Quality Management — customer specification compliance validation with deviation flagging per customer requirements.",
    "detail": "<p>Customer spec compliance:</p><ul><li><strong>Specifications</strong>: per customer: weight ranges, trim level, colour min, packaging</li><li><strong>Validation</strong>: output vs. customer spec for the allocated order</li><li><strong>Flagging</strong>: minor (within tolerance) or major (requires communication/reallocation)</li><li><strong>Reporting</strong>: compliance rate per customer, product, period</li></ul>"},
"PRC-055": {"code": "S", "summary": "Standard D365 document management — photo capture and attachment to batches and quality records via mobile or web.",
    "detail": "<p>Photo documentation:</p><ul><li><strong>Capture</strong>: via mobile — product samples, defects, equipment, packaging issues</li><li><strong>Attachment</strong>: to batch, quality order, NCR, or customer complaint</li><li><strong>Storage</strong>: SharePoint Online with version control</li><li><strong>Use</strong>: investigation, customer claims, audits, training</li></ul>"},

# ═══════════════════════════════════════════════════════════════
#  7.8  PROCESSING COST  (PRC-056 → PRC-060)
# ═══════════════════════════════════════════════════════════════
"PRC-056": {"code": "S", "summary": "Standard D365 production costing — processing cost per kg breakdown: material, labour, packaging, energy, depreciation, overhead.",
    "detail": "<p>Cost per kg:</p><ul><li><strong>Material</strong>: fish at generation cost or market price. Packaging at standard/actual</li><li><strong>Labour</strong>: from Time &amp; Attendance × rate</li><li><strong>Packaging</strong>: BOM consumption per order</li><li><strong>Energy</strong>: allocated per kg from plant metering</li><li><strong>Depreciation &amp; maintenance</strong>: from Asset Management</li><li><strong>Overhead</strong>: allocated by kg throughput or machine hours</li></ul>"},
"PRC-057": {"code": "S", "summary": "Standard D365 production costing — VAP product cost per unit/kg with salmon, ingredients, labour, packaging, and overhead per SKU.",
    "detail": "<p>VAP costing:</p><ul><li><strong>Recipe cost</strong>: BOM rollup: salmon, ingredients, packaging</li><li><strong>Labour</strong>: direct labour from time registrations</li><li><strong>Overhead</strong>: VAP-specific overhead per product/batch</li><li><strong>Unit cost</strong>: per unit or per kg for each ~120 SKU</li><li><strong>Variance</strong>: standard vs. actual per run</li></ul>"},
"PRC-058": {"code": "S", "summary": "Standard D365 inventory valuation — raw material (fish) at market price or accumulated production cost for margin analysis.",
    "detail": "<p>Raw material valuation:</p><ul><li><strong>Method</strong>: accumulated cost per generation (NRS 8 / GAAP) or market transfer price (IFRS / margin analysis)</li><li><strong>Support</strong>: Norwegian GAAP and IFRS methodologies</li><li><strong>Margin</strong>: processing margin calculable regardless of method</li><li><strong>Valuation</strong>: consistent with GL inventory account balances</li></ul>"},
"PRC-059": {"code": "S", "summary": "Standard D365 cost accounting — variance reporting: material yield, price, labour efficiency, and overhead spending vs. standard.",
    "detail": "<p>Variance reporting:</p><ul><li><strong>Material yield</strong>: (actual − standard yield) × cost</li><li><strong>Material price</strong>: (actual − standard cost) × quantity</li><li><strong>Labour</strong>: (actual − standard hours) × rate</li><li><strong>Overhead</strong>: actual − absorbed</li><li><strong>Reporting</strong>: per order, product, line, period in D365 and Power BI</li></ul>"},
"PRC-060": {"code": "C", "summary": "D365 costing + Power BI — break-even analysis per product with required price, scenarios, and decision support.",
    "detail": "<p>Break-even analysis:</p><ul><li><strong>Cost</strong>: fully loaded per kg from D365 costing</li><li><strong>Price</strong>: from trade agreements and market references</li><li><strong>Break-even</strong>: required price = cost ÷ (1 − target margin)</li><li><strong>Scenarios</strong>: Power BI what-if for price, yield, raw material sensitivity</li><li><strong>Decisions</strong>: spot pricing, contracts, product mix, investments</li></ul>"},

# ═══════════════════════════════════════════════════════════════
#  7.9  DISPATCH & SHIPPING  (PRC-061 → PRC-067)
# ═══════════════════════════════════════════════════════════════
"PRC-061": {"code": "S", "summary": "Standard D365 sales + WMS — dispatch planning based on confirmed orders, carrier schedules, and product readiness.",
    "detail": "<p>Dispatch planning:</p><ul><li><strong>Order-based</strong>: confirmed orders drive dispatch. Matched to available product</li><li><strong>Carrier</strong>: pickup times factored — product staged before arrival</li><li><strong>Readiness</strong>: only quality-released product dispatched</li><li><strong>Shipments</strong>: grouped by carrier, route, date, temperature class</li></ul>"},
"PRC-062": {"code": "S", "summary": "Standard D365 WMS — pick/pack with generated pick lists, scan-based confirmation, and case/pallet recording.",
    "detail": "<p>Pick/pack:</p><ul><li><strong>Pick wave</strong>: shipment generates pick work with FEFO batch selection</li><li><strong>Scanning</strong>: D365 mobile — scan location, scan SSCC confirms picked = ordered</li><li><strong>Packing</strong>: per specification. Weights confirmed, labels applied, pallets built</li><li><strong>Recording</strong>: pallet with SSCC, product, batch, count, weight, assigned order</li></ul>"},
"PRC-063": {"code": "S", "summary": "Standard D365 catch-weight — dispatch weight verification comparing shipment to order weight and pallet totals.",
    "detail": "<p>Weight verification:</p><ul><li><strong>Capture</strong>: final shipment weight from truck/pallet scales</li><li><strong>Reconciliation</strong>: vs. order weight, pallet sum, truck tare</li><li><strong>Discrepancy</strong>: beyond tolerance flagged before departure</li><li><strong>Documentation</strong>: verified weight on CMR, packing list</li></ul>"},
"PRC-064": {"code": "S", "summary": "Standard D365 document generation — Bill of Lading, CMR, airway bill data, commercial invoice, and packing list.",
    "detail": "<p>Shipping documents:</p><ul><li><strong>CMR</strong>: road transport — consignor, consignee, product, weight, terms</li><li><strong>BOL</strong>: sea freight — booking, container, product, terms</li><li><strong>Airway bill</strong>: air freight product/weight data</li><li><strong>Invoice</strong>: product, qty, weight, price, currency, Incoterms, tariff codes</li><li><strong>Packing list</strong>: per pallet: product, batch, cases, weight, SSCC</li></ul>"},
"PRC-065": {"code": "C", "summary": "D365 batch attributes + IoT — temperature logger assignment per shipment with data capture on return for cold chain.",
    "detail": "<p>Temperature loggers:</p><ul><li><strong>Assignment</strong>: logger device assigned at dispatch. ID recorded against shipment</li><li><strong>Data</strong>: on return/download, temperature time-series stored</li><li><strong>Verification</strong>: data reviewed for maintained range, excursions, durations</li><li><strong>Record</strong>: log attached to shipment. Excursions trigger investigation</li></ul>"},
"PRC-066": {"code": "C", "summary": "D365 + carrier integration — proof of delivery with date/time, receiver confirmation, exceptions, and invoice triggering.",
    "detail": "<p>Proof of delivery:</p><ul><li><strong>Confirmation</strong>: carrier provides POD: date/time, receiver, exceptions</li><li><strong>Integration</strong>: via API, EDI, or upload linked to D365 shipment</li><li><strong>Exceptions</strong>: short shipment, damage, temperature deviation, refusal → claims investigation</li><li><strong>Invoice</strong>: confirmed delivery triggers invoice for delivery-based terms</li></ul>"},
"PRC-067": {"code": "S", "summary": "Standard D365 batch tracing — full dispatch traceability: shipment/pallet/case → production batches → orders → transport details.",
    "detail": "<p>Dispatch traceability:</p><ul><li><strong>Forward</strong>: batch → cases → pallets → shipment → customer → delivery</li><li><strong>Backward</strong>: customer → shipment → pallet → cases → batch → intake → farm</li><li><strong>Recall</strong>: from batch → all shipments/customers. From shipment → all batches</li><li><strong>Transport</strong>: carrier, vehicle, route, times, temperature logger — full transport trace</li></ul>"},
}
